Projecte-UrbanTree/UrbanTree

.github/CODEOWNERS
Revise CODEOWNERS to reflect new team responsibilities and assign ownership of markdown files.
=> Update CODEOWNERS for team responsibilities and file ownership

src/app/Models/Worker.php, src/app/Views/Home.php, src/routes/web.php
Refactor the Worker model to utilize object methods for data retrieval and update the Home view accordingly. Add a new route for example functionality.
=> Refactor Worker model and update Home view with new route functionality

docker-compose.yml
Introduce a storage volume to ensure data persistence for the application.
=> fix(docker): add storage volume for persistent data

docker/database/start-scripts/0-init.sql, docker/database/start-scripts/1-seed.sql, src/app/Controllers/PruningTypeController.php, src/app/Models/PruningType.php, src/app/Views/PruningType.php
Introduce a new PruningType MVC for managing pruning types. Create the pruning_types table to meet the requirements, ensuring proper data handling and integrity.
=> feat(pruning-type): add PruningType 

src/app/Layouts/MainLayout.php, src/app/Views/Contracts.php, src/routes/web.php
Contract view made by Oriol added in this new estructure + item in nav menu.
=> feat(contract): add view, route and item in main layout

docker/database/start-scripts/1-seed.sql
Enhance the database seed script by adding entries for sensors and their history.
=> feat(database): update seed script to include sensors and sensor history

src/app/Core/Router.php, src/app/Views/Error/404.php
Added new handling 404 error
TODO: Add render ViewError to manage all status code errors
=> feat: add custom 404 error page and handling in router

src/app/Models/BaseModel.php
Improve method signatures in the base model to accommodate a wider range of data types.
=> feat(base-model): enhance method signatures to support additional data types

src/app/Controllers/ContractController.php, src/app/Models/BaseModel.php, src/app/Views/Contract/Create.php, src/app/Views/Contract/Edit.php, src/app/Views/Contracts.php, src/routes/web.php
This pull request includes significant changes to the `ContractController` and associated views, adding full CRUD (Create, Read, Update, Delete) functionality for contracts. The most important changes include the addition of new methods in the controller, updates to the views for creating and editing contracts, and modifications to the routes to support these new actions.
* [`src/app/Controllers/ContractController.php`](diffhunk://#diff-6bdec0be563d7baff057ed2d8ac4795d1172a1869bd86b85e5895c059a920c52R20-R81): Added methods `create`, `store`, `edit`, `update`, and `destroy` to handle contract creation, storage, editing, updating, and deletion respectively.
* [`src/app/Views/Contract/Create.php`](diffhunk://#diff-b660c0b23db00cc87b8468ad1ae1517f77e0ac7b7d873ff41ff35d6676826973R1-R71): Added …
=> feat(contract): add views

.github/workflows/docker.yml
This pull request includes enhancements to the Docker workflow configuration in the `.github/workflows/docker.yml` file. The changes focus on improving the efficiency of Docker builds by adding caching mechanisms and updating permissions.
Improvements to Docker workflow:
* Added steps to cache Docker layers using `actions/cache@v4` and `reproducible-containers/buildkit-cache-dance@4b2444fec0c0fb9dbf175a96c094720a692ef810` to optimize build times.
* Updated permissions to allow writing to contents and reading pull requests, ensuring the workflow has the necessary access to perform its tasks.
=> fix(ci): update CI workflow for Docker builds

.github/workflows/main.yml, .github/workflows/tests.yml, api/Dockerfile, api/src/config.py, api/src/main.py, api/tests/test_config.py, app/Dockerfile, compose.prod.yml
This pull request includes several changes to the GitHub Actions workflows, Dockerfiles, and configuration files to enhance the build and deployment process, as well as improve the configuration management. The key changes include updates to the GitHub Actions workflows, the introduction of environment variables in Dockerfiles, and modifications to the configuration settings and tests.
**GitHub Actions Workflows:**
* [`.github/workflows/main.yml`](diffhunk://#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3L22-R28): Updated the `cleanup` job to trigger on any closed event, added `version` output, and included `version` in build arguments and release steps. [[1]](diffhunk://#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3L22-R28) …
=> feat(ci): enhance release process with image versioning

.env.example, app/src/app/Layouts/Admin/AdminInventoryLayout.php, app/src/app/Views/Admin/Inventory.php, compose.yml
This pull request introduces several changes to integrate Mapbox for enhanced map functionality in the admin inventory layout and updates some environment configurations. The most important changes include adding Mapbox tokens and scripts, modifying the layout to include a map, and updating environment variables.
* [`app/src/app/Layouts/Admin/AdminInventoryLayout.php`](diffhunk://#diff-b481005a8bf0056c3738ef950fb32372eaa33d22fb19db149232f9883d0e6438R16-R29): Added Mapbox CSS and JS links, and a new style block to support the map display.
* [`app/src/app/Views/Admin/Inventory.php`](diffhunk://#diff-49896beb295cc25953c3fe96f89a435169c30cd89befecb4ba58ff9ca787c88bL1-R63): Replaced placeholder text with a Mapbox map, including initialization and configuration scripts for the map.
* …
=> feat: inventary with the map

app/src/app/Views/Admin/Contract/Create.php, app/src/app/Views/Admin/Contract/Edit.php, app/src/app/Views/Admin/Contracts.php, app/src/public/assets/js/app.js
Change labels from "Fecha de inicio" and "Fecha de fin" to "Fecha inicial" and "Fecha final" across the application for improved clarity and consistency.
=> refactor: update date labels from "Fecha de inicio" and "Fecha de fin" to "Fecha inicial" and "Fecha final"

app/src/app/Controllers/Admin/WorkOrderController.php, app/src/app/Models/WorkOrderBlockZone.php, app/src/app/Models/WorkOrderUser.php, app/src/app/Views/Admin/WorkOrder/Create.php, app/src/app/Views/Admin/WorkOrder/WorkOrders.php, app/src/public/assets/js/app.js
This pull request introduces several changes to the `WorkOrder` functionality in the admin panel, focusing on improving the creation and management of work orders. The changes include adding new models, updating the controller, and modifying the views to handle dynamic inputs and relationships.
* Added new model imports in `WorkOrderController.php` to handle work order blocks, tasks, users, and zones.
* Enhanced the `store` method to include error handling and to manage relationships between work orders, users, blocks, zones, and tasks.
* Introduced `WorkOrderBlockZone` model to manage the relationship between work order blocks and zones.
* Introduced `WorkOrderUser` model to manage the relationship between work orders and users.
* Updated the `Create.php` view to include hidden inputs …
=> feat: add create work order view and new models

app/src/app/Controllers/Admin/ContractController.php, app/src/app/Controllers/Admin/UserController.php, app/src/app/Controllers/Auth/AuthController.php, app/src/app/Core/Router.php, app/src/app/Core/View.php, app/src/app/Layouts/Admin/AdminInventoryLayout.php, app/src/app/Layouts/Admin/AdminLayout.php, app/src/app/Models/User.php, app/src/app/Views/Admin/User/Create.php, app/src/app/Views/Admin/User/Edit.php, app/src/app/Views/Admin/User/Users.php, app/src/public/assets/js/app.js, app/src/routes/admin.php
- Implemented the full **User CRUD** functionality with password hashing to ensure secure storage of user passwords.
- Integrated a **contract selection mechanism**, storing the selected contract in `$_SESSION` to maintain state across requests.
- Updated the session value dynamically to reflect the user's selected contract.
This update ensures:
1. User credentials are securely managed using password hashing.
2. The contract selection state persists consistently throughout the session.
=> refactor: user crud, password hashing and contract selection

app/src/app/Layouts/PublicLayout.php, app/src/app/Views/Admin/Contracts.php, app/src/app/Views/Admin/ElementTypes.php, app/src/app/Views/Admin/TaskTypes.php, app/src/app/Views/Admin/TreeTypes.php, app/src/app/Views/Admin/Users.php, app/src/app/Views/Admin/WorkOrders.php, app/src/app/Views/License.php, app/src/public/assets/css/app.css
This PR fixes multiple design and layout issues introduced after the recent update:  
- 🛠️ Fixed Cookie Consent banner styles to load correctly on the public layout.  
- 🛠️ Adjusted button placement to be outside the `overflow-x` div.  
- 🛠️ Added `overflow-x: scroll` to `<pre>` in the license view.  
- 🎨 Refactored return button location and removed unused Tailwind classes.
=> fix: design errors after big design and layout update

app/src/app/Layouts/Admin/AdminInventoryLayout.php, app/src/app/Layouts/Admin/AdminLayout.php, app/src/app/Layouts/AuthLayout.php, app/src/app/Layouts/PublicLayout.php
Replace the FontAwesome CDN kit link.
=> refactor: update FontAwesome CDN kit link

app/src/app/Controllers/Admin/AccountController.php, app/src/app/Views/Admin/Account.php, app/src/public/assets/js/app.js
Enhance change detection logic for form inputs and improve button state management during password changes.
=> refactor: validate password change and input handling

app/src/app/Controllers/Api/MapController.php, app/src/app/Views/Admin/Inventory.php, app/src/public/assets/js/map.js, app/src/routes/api.php, database/start-scripts/1-seed.sql
This pull request includes several updates to the `MapController` and related files to improve functionality and consistency. The changes primarily focus on adding JSON response headers, refactoring code for better readability, and updating the database schema for elements.
Improvements to API responses:
* [`app/src/app/Controllers/Api/MapController.php`](diffhunk://#diff-f1fda11aa6412f7857220d2a1adf4f734b00204d71e4728150ec27989eb92548R71-R72): Added `header('Content-Type: application/json');` at the beginning of multiple methods to ensure all responses are in JSON format. [[1]](diffhunk://#diff-f1fda11aa6412f7857220d2a1adf4f734b00204d71e4728150ec27989eb92548R71-R72) [[2]](diffhunk://#diff-f1fda11aa6412f7857220d2a1adf4f734b00204d71e4728150ec27989eb92548R102-R103) …
=> refactor: enhance map adding information modal, change visibility icon and store element description

app/src/app/Controllers/Admin/TreeTypeController.php, app/src/app/Layouts/Admin/AdminInventoryLayout.php, app/src/app/Layouts/Admin/AdminLayout.php, app/src/app/Layouts/AuthLayout.php, app/src/app/Layouts/PublicLayout.php, app/src/app/Views/Admin/Account.php, app/src/app/Views/Admin/Contracts.php, app/src/app/Views/Admin/Dashboard.php, app/src/app/Views/Admin/ElementType/Create.php, app/src/app/Views/Admin/ElementType/Edit.php, app/src/app/Views/Admin/ElementTypes.php, app/src/app/Views/Admin/Inventory.php, app/src/app/Views/Admin/TaskTypes.php, app/src/app/Views/Admin/TreeType/Create.php, app/src/app/Views/Admin/TreeType/Edit.php, app/src/app/Views/Admin/TreeTypes.php, app/src/app/Views/Admin/Users.php, app/src/app/Views/Admin/WorkOrders.php, app/src/app/Views/Auth/Login.php, app/src/public/assets/css/app.css
This pull request includes several changes across multiple files to update terminology and improve the user interface. The most important changes include updating the term "Tipo de Árbol" to "Especie" and modifying icons and layout styles in various admin layout files.
Terminology updates:
* [`app/src/app/Controllers/Admin/TreeTypeController.php`](diffhunk://#diff-19a86eb9a78145a8eb8e77af544a82123ada3a82dad8f6b64d75351fb7f5ac68L16-R16): Updated multiple instances of "Tipo de Árbol" to "Especie" in titles and messages. [[1]](diffhunk://#diff-19a86eb9a78145a8eb8e77af544a82123ada3a82dad8f6b64d75351fb7f5ac68L16-R16) [[2]](diffhunk://#diff-19a86eb9a78145a8eb8e77af544a82123ada3a82dad8f6b64d75351fb7f5ac68L26-R26) [[3]](diffhunk://#diff-19a86eb9a78145a8eb8e77af544a82123ada3a82dad8f6b64d75351fb7f5a …
=> refactor: update layout and styling, change menu icons and some tweaks

.github/workflows/database.yml
This pull request includes an important update to the database seeding process in the GitHub Actions workflow file. The most significant change is the addition of a step to seed the database.
Enhancements to the database workflow:
* [`.github/workflows/database.yml`](diffhunk://#diff-6d533b8715476f7360b06e09b2bfdecef3d18ea00116ddb7390435858ff10859R29-R31): Added a new step to seed the database using a secret environment variable.
**This seed will replace the develop seed file.**
=> chore: add database secret seeding step in workflow

app/src/public/assets/js/map.js, database/start-scripts/1-seed.sql
This pull request includes several changes to the `app/src/public/assets/js/map.js` file, focusing on code cleanup and functionality improvements. The most important changes include removing console log statements, simplifying event listeners, and enhancing the map's zone and element management.
Code cleanup and simplification:
* Removed console log statements to clean up the code and reduce unnecessary logging. [[1]](diffhunk://#diff-d2f8c0dc39fe7cb3f67aa82664539e919c4e2808c40623faa083908c5349aaeeL227) [[2]](diffhunk://#diff-d2f8c0dc39fe7cb3f67aa82664539e919c4e2808c40623faa083908c5349aaeeL642) [[3]](diffhunk://#diff-d2f8c0dc39fe7cb3f67aa82664539e919c4e2808c40623faa083908c5349aaeeL906)
* Simplified event listeners by removing redundant code.
Functionality improvements:
* Enhanced the …
=> fix(map): bugs found after big map update

app/src/app/Controllers/Api/MapController.php, app/src/app/Models/Sensor.php, app/src/public/assets/js/map.js, database/start-scripts/0-init.sql
This pull request includes several changes to the `MapController`, `Sensor` model, JavaScript handling of map elements, and SQL initialization scripts to improve functionality and data handling. The most important changes include updating the `hasIncidence` property, removing the `class` property from the `Sensor` model, and adding a map reload function after incidence status changes.
* [`app/src/app/Controllers/Api/MapController.php`](diffhunk://#diff-f1fda11aa6412f7857220d2a1adf4f734b00204d71e4728150ec27989eb92548L59-R59): Updated the `hasIncidences` property to `hasIncidence` and modified the condition to check for open incidences only.
* [`app/src/app/Models/Sensor.php`](diffhunk://#diff-ce48056f2821eb6346a3a522ff3e4247c088f12de22e546fee69b3308946edfcL13-L14): Removed the `class` …
=> fix: update incidence check to filter by open status and adjust related variable naming

app/src/public/assets/js/map.js
This pull request includes changes to the `app/src/public/assets/js/map.js` file to improve the API connection handling. The most important changes include the introduction of a constant for the API connection string and updating the sensor history fetch URL to use this constant.
Improvements to API connection handling:
* [`app/src/public/assets/js/map.js`](diffhunk://#diff-d2f8c0dc39fe7cb3f67aa82664539e919c4e2808c40623faa083908c5349aaeeR2-R3): Added a new constant `API_CONNECTION` to store the API connection string.
* [`app/src/public/assets/js/map.js`](diffhunk://#diff-d2f8c0dc39fe7cb3f67aa82664539e919c4e2808c40623faa083908c5349aaeeL715-R717): Updated the `fetchSensorHistory` function to use the `API_CONNECTION` constant for constructing the API URL.
=> fix: update API connection string for fetching sensor history
