docker/mariadb/start-scripts/init.sql

This pull request adds the necessary SQL code to create the required database tables and their relationships. The tables include 'points', 'zones', 'elements', 'inventory', 'incidences', 'roles', 'workers', 'work_orders', 'machines', 'parts', 'routes', 'tasks', 'workers_task', 'sensor', and 'sensorhistory'. These tables define the structure and relationships of the database entities needed for the application.

Add database tables and relationships

---

docker/server/Dockerfile

Resolve casing mismatch warnings in the Dockerfile by updating the keywords to use consistent uppercase formatting.

Fix Dockerfile casing warnings

---

.dockerignore
docker-compose.yml
docker/server/Dockerfile

Improve Docker setup by adding a .dockerignore file, commenting out the database volume configuration, and enhancing the Dockerfile with PECL extensions and Xdebug support.

Enhance Docker configuration and add Xdebug support

---

Dockerfile
docker-compose.yml
src/app/Core/Database.php

Ensure that start-scripts run on each restart of the database container by creating a dedicated database stage in the Dockerfile. Adjust the database service configuration to build from this stage and utilize a temporary filesystem for development.
The database service will restart when detects changes on any file of `docker\database\start-scripts`, allowing scripts to be executed.
Switching between branches was annoying because we need to delete the service, while now it is no longer necessary, because it will update automatically if it detects changes.

fix(docker-database): improve behavior so that initialization scripts are executed every time a file changes

---

Dockerfile
README.md
docker/database/start-scripts/0-init.sql

Update Dockerfile for development stage, enhance README installation instructions, and modify database schema to include point_id in sensors table.

Release for Sprint 2

---

src/app/Models/TaskType.php

Revert the previous change that removed the assignment of `created_at` during task creation to ensure the timestamp is correctly set.

revert(TaskType): restore created_at assignment in task creation

---

.github/dependabot.yml

Introduce a Dependabot configuration to automate version updates for Composer, Docker, and GitHub Actions on a weekly schedule.

feat: add Dependabot configuration for version updates

---

src/app/Models/BaseModel.php
src/app/Models/Route.php

This pull request focuses on improving type safety and return types in the `BaseModel` and `Route` classes. The changes ensure that methods have explicit type hints for their parameters and return types, which enhances code readability and reduces potential runtime errors.
Key changes include:
* [`src/app/Models/BaseModel.php`](diffhunk://#diff-878584d507d415f0091c62359e679487aa677d2b84830e88421dfa26f7888124L97-R97): Updated method signatures to include type hints for parameters and return types. This affects methods such as `count`, `exists`, `find`, `findAll`, `findBy`, `findSoftDeleted`, `hasOne`, `paginate`, and abstract methods `getTableName` and `mapDataToModel`. [[1]](diffhunk://#diff-878584d507d415f0091c62359e679487aa677d2b84830e88421dfa26f7888124L97-R97) …

feat(base-model): update method signatures to allow nullable return types

---

database/start-scripts/0-init.sql

Introduce `updated_at` and `deleted_at` timestamp columns to various database tables for better tracking of record modifications and soft deletion capabilities.

feat(database): add updated_at and deleted_at columns to multiple tables

---

src/app/Views/Admin/TreeType/Create.php
src/app/Views/Admin/TreeType/Edit.php
src/app/Views/Admin/TreeTypes.php

This pull request includes changes to the URLs in several files to ensure they follow a consistent structure by adding the `/admin` prefix. The most important changes include updates to the `Create`, `Edit`, and `TreeTypes` views.
URL updates for consistency:
* [`src/app/Views/Admin/TreeType/Create.php`](diffhunk://#diff-b5fc91cbc00701c4904cf5380e8153db0cb8385cb26d21626594cd6c5947df06L2-R2): Updated the form action URL to `/admin/tree-type/store` and the back link URL to `/tree-types/`. [[1]](diffhunk://#diff-b5fc91cbc00701c4904cf5380e8153db0cb8385cb26d21626594cd6c5947df06L2-R2) [[2]](diffhunk://#diff-b5fc91cbc00701c4904cf5380e8153db0cb8385cb26d21626594cd6c5947df06L14-R14)
* [`src/app/Views/Admin/TreeType/Edit.php`](diffhunk://#diff-9d33f489f9fadfeea6be89d03ffc68c7262d2cd5622b87c8f986b4e05 …

fix(tree-types): update links from create, edit and delete

---

.env.example
.github/workflows/main.yml
api/Dockerfile
api/requirements.txt
api/src/app.py
api/src/config.py
api/tests/test_config.py
compose.yml

This pull request introduces several changes to integrate Sentry for error monitoring and improve environment configuration to the API. The key changes include adding Sentry DSN variables, updating Docker and FastAPI configurations, and creating tests for the new settings.
* [`.env.example`](diffhunk://#diff-a3046da0d15a27e89f2afe639b25748a7ad4d9290af3e7b1b6c1a5533c8f0a8cR13-R16): Added `SENTRY_DSN_API` and `SENTRY_DSN_APP` environment variables for Sentry integration.
* [`api/requirements.txt`](diffhunk://#diff-f380e1392f38d13c3831f35c9f505277739b484c035bc791c21cc6d081845607R8): Added `sentry-sdk[fastapi]==2.19.0` to dependencies.
* [`api/src/app.py`](diffhunk://#diff-f5e838a574b5fb82ba7600e7be68894c5c9f6a24cae7c0b04fd7ae57139afa17R2-R21): Initialized Sentry SDK with DSN and environment …

feat(api): integrate Sentry for error tracking and monitoring

---

api/src/config.py
api/src/main.py
api/tests/test_config.py

This pull request includes changes to the `api/src` and `api/tests` directories to modify how the `IMAGE_VERSION` is handled and to remove the `SENTRY_RELEASE` property. The changes ensure that the `IMAGE_VERSION` always starts with a 'v' prefix and simplify the configuration settings.
Configuration changes:
* [`api/src/config.py`](diffhunk://#diff-7df7ccee5a6672bf04f67eebb5964559fbbf239d77f594c8756ba3110e56fae0L35-R36): Modified the `check_image_version` method to ensure the `IMAGE_VERSION` starts with a 'v' prefix. Removed the `SENTRY_RELEASE` property from the `Settings` class. [[1]](diffhunk://#diff-7df7ccee5a6672bf04f67eebb5964559fbbf239d77f594c8756ba3110e56fae0L35-R36) [[2]](diffhunk://#diff-7df7ccee5a6672bf04f67eebb5964559fbbf239d77f594c8756ba3110e56fae0L78-L83)
Usage updates:
* …

fix(api): update image version handling and remove SENTRY_RELEASE property

---

.github/workflows/cd.yml
api/src/config.py
api/tests/test_config.py

This pull request includes changes to the continuous deployment workflow and the configuration settings for image versions. The most important changes include updating the workflow output version format and modifying the image version handling in the configuration and tests.
* [`.github/workflows/cd.yml`](diffhunk://#diff-ea3ea8c9932adc7ba8161ceda844fedd43b006848ef1140c050cbd7ea0788a18L25-R25): Updated the workflow output to use `steps.release.outputs.version` instead of `steps.release.outputs.tag_name`.
* [`api/src/config.py`](diffhunk://#diff-7df7ccee5a6672bf04f67eebb5964559fbbf239d77f594c8756ba3110e56fae0L35-R36): Modified the `check_image_version` method to strip the 'v' prefix from image versions if present.
* [`api/tests/test_config.py`](diffhunk://#diff-9c77b4f9a6f75032e644de8b5d501 …

fix(workflows): update output variable for version in CD workflow

---

.github/workflows/cd.yml

This pull request includes changes to the `.github/workflows/cd.yml` file to improve the versioning process in the CD pipeline. The most important changes are listed below:
Improvements to versioning process:
* Changed the output parameter `version` to use the `version` step instead of the `release` step.
* Removed the `tag_prefix` parameter from the `release` step configuration.
* Replaced the `Check Output Parameters` step with a new step named `Set the version` to extract and set the version from the tag name.

fix(workflows): update version output step in CD workflow

---

app/src/app/Controllers/Admin/ElementTypeController.php
app/src/app/Models/BaseModel.php
app/src/app/Models/Contract.php
app/src/app/Models/Element.php
app/src/app/Models/ElementType.php
app/src/app/Models/Incidence.php
app/src/app/Models/Machine.php
app/src/app/Models/Photo.php
app/src/app/Models/Point.php
app/src/app/Models/PruningType.php
app/src/app/Models/Role.php
app/src/app/Models/Route.php
app/src/app/Models/Sensor.php
app/src/app/Models/SensorHistory.php
app/src/app/Models/Task.php
app/src/app/Models/TaskType.php
app/src/app/Models/TreeType.php
app/src/app/Models/User.php
app/src/app/Models/WorkOrder.php
app/src/app/Models/WorkReport.php
app/src/app/Models/Zone.php
app/src/app/Models/ZonePredefined.php
app/src/app/Views/Admin/ElementType/Create.php
app/src/app/Views/Admin/ElementType/Edit.php
app/src/app/Views/Admin/ElementTypes.php
app/src/routes/admin.php

This pull request includes significant changes to the `app/src/app` directory, focusing on the addition of new fields and methods to various model classes and the creation of a new controller for managing element types.
* [`app/src/app/Controllers/Admin/ElementTypeController.php`](diffhunk://#diff-b853c2d8221709f16b1628ada40365adee6d7d67e0e85a419e63566f096b2318R1-R81): Added a new controller with methods for CRUD operations on element types.
* [`app/src/app/Models/BaseModel.php`](diffhunk://#diff-57d475838e6428c42c3b9d5c460bea147ffb64f834e6ff8e980d351bf00c5c77R13-R16): Added `updated_at` and `deleted_at` fields and their respective getter methods. [[1]](diffhunk://#diff-57d475838e6428c42c3b9d5c460bea147ffb64f834e6ff8e980d351bf00c5c77R13-R16) …

feat: create ElementType

---

app/src/app/Layouts/Admin/AdminLayout.php
app/src/app/Views/Admin/Users.php
app/src/app/Views/Admin/WorkOrders.php
app/src/public/assets/js/tailwind.js

This pull request includes various updates to the layout and styling of the admin interface, focusing on improving the user experience and visual consistency.
Improvements to layout and navigation:
* [`app/src/app/Layouts/Admin/AdminLayout.php`](diffhunk://#diff-e43b091c2e5f4ff0f2b90b03cfee557777f5d3df706873e74b366fa34d9aa051L17-R26): Simplified the navigation bar by removing the mobile menu button and adjusted the submenu to be more responsive and visually consistent. [[1]](diffhunk://#diff-e43b091c2e5f4ff0f2b90b03cfee557777f5d3df706873e74b366fa34d9aa051L17-R26) [[2]](diffhunk://#diff-e43b091c2e5f4ff0f2b90b03cfee557777f5d3df706873e74b366fa34d9aa051L109-R101)
Styling updates:
* [`app/src/app/Layouts/Admin/AdminLayout.php`](diffhunk://#diff-e43b091c2e5f4ff0f2b90b03cfee557777f5d3df706873e74b …

fix(layouts): improve admin layout with stick navbar mobile

---

app/src/app/Views/Admin/Contract/Edit.php
app/src/app/Views/Admin/TreeType/Create.php
app/src/app/Views/Admin/TreeType/Edit.php

Correct the typo in the `text-red` class to `text-red-700` for consistent error message styling across multiple forms.

fix: typo in text-red class for error messages in forms

---

.github/labeler.yml
LICENSE

This pull request includes updates to the license and labeling configuration. The most important changes are the addition of a new license and the introduction of a new labeling rule for documentation-related branches.
* [`LICENSE`](diffhunk://#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7R1-R287): Added the European Union Public Licence (EUPL) v. 1.2 to the project, detailing the terms and conditions for use, reproduction, modification, and distribution of the work.
* [`.github/labeler.yml`](diffhunk://#diff-a22c263686553013feaeb0677d26eeb0b8778a756c4311c1fce13384258026aaR59-R61): Introduced a new labeling rule `kind/docs` for branches starting with `docs/` to categorize documentation-related changes.

docs: add EUPL license

---

app/src/app/Core/View.php

This pull request includes a small change to the `app/src/app/Core/View.php` file. The change ensures that any 'success' or 'error' messages in the session are removed after rendering the view.
* [`app/src/app/Core/View.php`](diffhunk://#diff-8e660a412baa16e6f91dcba39b61a3af90782cb2f1a31ae38a72f115bf539af4R30-R37): Added checks to remove 'success' and 'error' messages from the session if they exist.

fix: :ambulance: remove success and error messages from session after view render

---

app/src/app/Views/Admin/Inventory.php

This pull request introduces a new feature to the `app/src/app/Views/Admin/Inventory.php` file, which enhances the user experience by utilizing the user's geolocation to interact with the map.
Geolocation feature:
* Added code to obtain the user's current position using the `navigator.geolocation.getCurrentPosition` method, and create a marker on the map at the user's location.
* Included functionality to center the map on the user's location and adjust the zoom level for better visibility.
* Implemented error handling to log any issues encountered while obtaining the user's location.
* Configured geolocation options for higher accuracy, a timeout limit, and to always use fresh data.

feat: map user geolocation

---

app/src/public/assets/js/app.js

This pull request includes several updates to the `app/src/public/assets/js/app.js` file, focusing on renaming CSS class names for better clarity and adding new functionalities to improve the user experience. The most important changes are listed below:
* Renamed the CSS class from `block` to `workorder-block` for better clarity and consistency in the `addBlock`, `addTask`, and `updateBlock` functions. [[1]](diffhunk://#diff-e67bfff488262a602130efec42c6e8bc5aa33a08896652f65654582b0d354ef7L415-R420) [[2]](diffhunk://#diff-e67bfff488262a602130efec42c6e8bc5aa33a08896652f65654582b0d354ef7L460-R458) [[3]](diffhunk://#diff-e67bfff488262a602130efec42c6e8bc5aa33a08896652f65654582b0d354ef7R492-R496)
* Added a check to automatically add a block if none exist when the document is loaded.
* …

fix(work-order): avoid duplication of blocks/tasks and correct updateBlocks

---

app/src/app/Controllers/Auth/AuthController.php
database/start-scripts/1-seed.sql

This PR fixes an issue where logging in resulted in a 500 error if no valid contracts were found.  
The problem was caused by seeder contract dates being identical and older than the current date, leaving `current_contract` as `null` in the session.

fix: error 500 when not valid contracts found

---

app/src/app/Controllers/Admin/UserController.php

This pull request includes important changes to the `UserController` in the `app/src/app/Controllers/Admin` directory. These changes add checks to ensure that the last administrator cannot have their role changed or be deleted.
Key changes include:
* **Role Change Verification**:
* In the `update` method, added a check to prevent changing the role of the last remaining administrator. If there is only one administrator and the role is being changed, an error message is set and the process is halted.
* **Deletion Verification**:
* In the `destroy` method, added a check to prevent deleting the last remaining administrator. If there is only one administrator, an error message is set and the user is not deleted.

fix: prevent modification and deletion of the only admin user

---

app/src/public/assets/js/map.js
database/start-scripts/1-seed.sql

This pull request includes various changes to the `app/src/public/assets/js/map.js` file to improve code readability and functionality, as well as updates to `database/start-scripts/1-seed.sql` to correct and streamline the initial data seeding process. The most important changes include removing unnecessary console logs, adding functionality to hide buttons, and updating the initial database seeding script to correct data entries.
Improvements to `map.js`:
* Removed unnecessary console logs to clean up the code (`app/src/public/assets/js/map.js`). [[1]](diffhunk://#diff-d2f8c0dc39fe7cb3f67aa82664539e919c4e2808c40623faa083908c5349aaeeL227) [[2]](diffhunk://#diff-d2f8c0dc39fe7cb3f67aa82664539e919c4e2808c40623faa083908c5349aaeeL642) …

fix(map): bugs and tweaks to improve usability

---

app/src/app/Models/WorkOrder.php
app/src/app/Views/Worker/WorkOrders.php

This pull request includes updates to the `WorkOrder` model and the `WorkOrders` view to improve data handling and user experience. The most important changes are:
* [`app/src/app/Models/WorkOrder.php`](diffhunk://#diff-b2a8b4d76a56d0ba0e5f297563bc8c27faa689d914445ae6697f019e20e4e2a4L29-R29): Modified the `report` method to return a nullable `WorkReport` object, ensuring compatibility when no report is associated with the work order.
* [`app/src/app/Views/Worker/WorkOrders.php`](diffhunk://#diff-e562e3af2c2629c5161f827c2563c380411b24f2427a2a1d4d4e3ebcb92e1f10L171-R171): Updated the `observation` textarea to handle cases where the `observation` property might be null, preventing potential errors in rendering the view.

fix: update WorkOrder model to allow nullable WorkReport and handle observation safely
